attention_head_size: 4
categorical_groups: {}
causal_attention: true
dropout: 0.1
embedding_labels: {}
embedding_paddings: []
embedding_sizes: {}
hidden_continuous_size: 8
hidden_continuous_sizes: {}
hidden_size: 16
learning_rate: 0.03
log_gradient_flow: false
log_interval: 10
log_val_interval: null
lstm_layers: 1
max_encoder_length: 24515
monotone_constaints: {}
optimizer: Ranger
optimizer_params: null
output_size: 7
output_transformer: !!python/object:pytorch_forecasting.data.encoders.NaNLabelEncoder
  add_nan: false
  classes_:
    ? !!python/object/apply:numpy.core.multiarray.scalar
    - &id001 !!python/object/apply:numpy.dtype
      args:
      - i8
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - -1
      - -1
      - 0
    - !!binary |
      AQAAAAAAAAA=
    : 0
    ? !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      AgAAAAAAAAA=
    : 1
    ? !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      AwAAAAAAAAA=
    : 2
    ? !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      BAAAAAAAAAA=
    : 3
    ? !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      BQAAAAAAAAA=
    : 4
  classes_vector_: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - !!python/name:numpy.ndarray ''
    - !!python/tuple
      - 0
    - !!binary |
      Yg==
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 5
    - *id001
    - false
    - !!binary |
      AQAAAAAAAAACAAAAAAAAAAMAAAAAAAAABAAAAAAAAAAFAAAAAAAAAA==
  warn: true
reduce_on_plateau_min_lr: 1.0e-05
reduce_on_plateau_patience: 1000
reduce_on_plateau_reduction: 2.0
share_single_variable_networks: false
static_categoricals: []
static_reals:
- encoder_length
time_varying_categoricals_decoder: []
time_varying_categoricals_encoder: []
time_varying_reals_decoder:
- relative_time_idx
time_varying_reals_encoder:
- relative_time_idx
weight_decay: 0.0
x_categoricals: []
x_reals:
- encoder_length
- relative_time_idx
