embeddings {
  tensor_name: "agency:00850"
  metadata_path: "00850/agency/metadata.tsv"
  tensor_path: "00850/agency/tensors.tsv"
}
embeddings {
  tensor_name: "sku:00850"
  metadata_path: "00850/sku/metadata.tsv"
  tensor_path: "00850/sku/tensors.tsv"
}
embeddings {
  tensor_name: "special_days:00850"
  metadata_path: "00850/special_days/metadata.tsv"
  tensor_path: "00850/special_days/tensors.tsv"
}
embeddings {
  tensor_name: "month:00850"
  metadata_path: "00850/month/metadata.tsv"
  tensor_path: "00850/month/tensors.tsv"
}
